//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication29.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietXe
    {
        public int MaChiTiet { get; set; }
        public int MaXe { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
    
        public virtual Xe Xe { get; set; }
    }
}
