//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication29.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThue
    {
        public int MaDon { get; set; }
        public int MaNguoiDung { get; set; }
        public int MaXe { get; set; }
        public string DiemNhan { get; set; }
        public string DiemTra { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
