//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication29.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoXe
    {
        public int MaThongSo { get; set; }
        public int MaXe { get; set; }
        public string TenThongSo { get; set; }
        public string GiaTri { get; set; }
    
        public virtual Xe Xe { get; set; }
    }
}
