//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication29.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Xe()
        {
            this.ChiTietXes = new HashSet<ChiTietXe>();
            this.DanhGias = new HashSet<DanhGia>();
            this.DonThues = new HashSet<DonThue>();
            this.ThongSoXes = new HashSet<ThongSoXe>();
            this.XeYeuThiches = new HashSet<XeYeuThich>();
        }
    
        public int MaXe { get; set; }
        public string TenXe { get; set; }
        public string HangXe { get; set; }
        public string LoaiXe { get; set; }
        public Nullable<decimal> GiaMoiNgay { get; set; }
        public string NhienLieu { get; set; }
        public string HopSo { get; set; }
        public Nullable<int> SoChoNgoi { get; set; }
        public string AnhXe { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> NoiBat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietXe> ChiTietXes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonThue> DonThues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoXe> ThongSoXes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeYeuThich> XeYeuThiches { get; set; }
    }
}
